package com.sample.rules
 
 import com.sample.ProposalInitiation;
  import com.sample.DocumentInfo;
import java.util.HashMap;  

import java.util.*;  
import java.io.*;  

rule "Inital_set_up"
no-loop
ruleflow-group "Inital_set_up"
when	
     p:ProposalInitiation(p.CustID != null);
  
then	
 		System.out.println("Customer Name\t"+p.getCustomerName());
 		System.out.println("Customer Name\t"+p.getProposedTotalLimit());
 		System.out.println("Customer Name\t"+p.getInputterDT());
 		
 		
 		
end


rule "Read_Registration"
no-loop
ruleflow-group "Read_Registration"
when	
      p:ProposalInitiation(p.CustID != null);	
then	
			for(int i=0;i<p.getRegistrationDetails().size();i++){
			System.out.println(p.getRegistrationDetails().get(i));
			}
end



rule "Read_Document"
no-loop
ruleflow-group "Read_Document"
when	
      p:ProposalInitiation(p.CustID != null);
      d:DocumentInfo(d.DocCD != null);	
then	
			for(int i=0;i<p.getDocInformation().size();i++){
			d=p.getDocInformation().get(i);
			System.out.println("DocCD\t"+d.getDocCD());
			System.out.println("DocCD\t"+d.getDocGRPCD());
			}
end
